### ISSUE TITLE
Tracking issue - Multi-app run enhancements

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#1240]
## Describe the proposal
- [ ] https://github.com/dapr/cli/issues/1220
- [ ] https://github.com/dapr/cli/issues/1221
- [ ] https://github.com/dapr/cli/issues/1228
- [ ] https://github.com/dapr/cli/issues/1204
- [ ] https://github.com/dapr/cli/issues/1144
- [ ] https://github.com/dapr/cli/issues/1145
- [ ] https://github.com/dapr/cli/issues/1146
- [ ] https://github.com/dapr/cli/issues/1147
- [ ] https://github.com/dapr/cli/issues/1154
- [ ] https://github.com/dapr/cli/issues/1155

## Release Note

RELEASE NOTE:

**Comment by mcrio** [comment]
Hi @mukundansundar I wasn't aware of this topic so copying my comment from [another one](https://github.com/dapr/dapr/issues/6200) which is closed in favor of this one:

First I would like to thank the contributor for providing this feature :)

Use case: Start multiple .net based services and their Dapr sidecars during development. Previously I used Tye (no longer maintained).

What I like so far:

- Faster startup time compared to Tye
- Easy Yaml config

What I am having some difficulties with:

- After running dapr run in case some service fails to start that is not indicated in the CLI output.
- Logs have a hard coded path, namely the projects .dapr/logs subdirectory.
- It's not very easy to hunt for the logs in different folders and files, especially as each run generates new files.
