### ISSUE TITLE
Developer experience updates

### ISSUE THREAD

**Issue by orizohar** [dapr/cli#343]
This is an Epic issue that is meant to aggregate a set of changes that address new user feedback on friction points and easier use of dapr. The following sub issues are included in the epic:

- [x] Move default `components` directory creation from `dapr run` to `dapr init`. https://github.com/dapr/cli/issues/340

- [x] Add a flag to allow running `dapr init` without spinning up docker containers https://github.com/dapr/cli/issues/175 

- [x] `dapr dashboard` - New command that runs the dapr dashboard locally https://github.com/dapr/cli/issues/341

- [x] Add Zipkin as a container that is spun up during `dapr init` https://github.com/dapr/cli/issues/342

**Comment by vinayada1** [comment]
Done
